// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoppy.Persistence;

#nullable disable

namespace Shoppy.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240516042311_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserIdentityRole<Guid>", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentityRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserId", "IdentityRoleId");

                    b.HasIndex("IdentityRoleId");

                    b.ToTable("AppUserIdentityRole<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("85d8a27f-9d32-4269-b5d0-844589d498d0"),
                            RoleId = new Guid("5fc71af5-0216-402b-a5cb-ba17701e2fa3")
                        },
                        new
                        {
                            UserId = new Guid("021657c8-d4d0-4167-a1a6-b7bb840f33bf"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("2c96fabb-f759-43ef-9a31-328c25d2eff5"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("30a4345d-df2e-46ab-8c0e-d38a7933b591"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        },
                        new
                        {
                            UserId = new Guid("594f8fe1-1cf1-4f5a-a8ae-6b9509fbf283"),
                            RoleId = new Guid("8bbf66a4-da08-4b87-bdb2-1502e38562f3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AvgRate")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NumberOfPage")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSale")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ProductThumbUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsDelete");

                    b.HasIndex("Name");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2baf4c50-c927-4b54-971e-3ff5f300e147"),
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4905),
                            Name = "Romance",
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4909)
                        },
                        new
                        {
                            Id = new Guid("99ada3c1-eea5-4431-a529-b3114de224da"),
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4922),
                            Name = "Economic",
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4923)
                        },
                        new
                        {
                            Id = new Guid("adf36edc-3e08-4a36-8e20-0d79747f0962"),
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4925),
                            Name = "Business and Money",
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4926)
                        },
                        new
                        {
                            Id = new Guid("292c90a5-1a0a-45a4-8f3d-37f09b09b422"),
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4928),
                            Name = "History",
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4928)
                        },
                        new
                        {
                            Id = new Guid("97cf6bd7-7290-449a-a61d-5ea2fdfcf8de"),
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4931),
                            Name = "Education and Teacher",
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 309, DateTimeKind.Utc).AddTicks(4931)
                        });
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.ProductRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RateValue")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductRatings");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.RatingResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("RatingResources");
                });

            modelBuilder.Entity("Shoppy.Persistence.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasFilter("[CartId] IS NOT NULL");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("Gender");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("IsDelete", "NormalizedEmail");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("85d8a27f-9d32-4269-b5d0-844589d498d0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "370ffe5f-d018-43cb-b74c-a3882450d6eb",
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 743, DateTimeKind.Utc).AddTicks(3906),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FullName = "John Doe",
                            Gender = 1,
                            IsDelete = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEw9XBX2FqIO+9uBEtvpn2+WxfcJNSrUvcR6LUeVY62vWaNRKbw5bofAOJyhiohPEQ==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "https://avatarfiles.alphacoders.com/151/thumb-151233.jpg",
                            SecurityStamp = "e0c901cb-37e8-4a77-aa11-1ecb9ea6f997",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 743, DateTimeKind.Utc).AddTicks(3909),
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("021657c8-d4d0-4167-a1a6-b7bb840f33bf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7104da5-e09f-42cf-ba4e-162437dc154c",
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 863, DateTimeKind.Utc).AddTicks(8385),
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Jane Smith",
                            Gender = 1,
                            IsDelete = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "USER1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELrgHw93+kVe+DFKBiHKoBSI5svSzm9VW8OTRtEkoyKQPPjtoqHHNqxctOpDMBSKiA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "https://avatarfiles.alphacoders.com/151/thumb-151233.jpg",
                            SecurityStamp = "555a1a8b-977e-4e71-a788-98885c7d8a16",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 863, DateTimeKind.Utc).AddTicks(8388),
                            UserName = "user1@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("2c96fabb-f759-43ef-9a31-328c25d2eff5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cea0bff0-aaec-4b36-983c-3087decdaf29",
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 983, DateTimeKind.Utc).AddTicks(4813),
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Michael Johnson",
                            Gender = 2,
                            IsDelete = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "USER2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBspFaCOirbWf+cLwVVx7UsHZ6RKRfohufM/ONVt0k0GoQ0J0pa1zBBUV3lDPdTpfA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "https://avatarfiles.alphacoders.com/151/thumb-151233.jpg",
                            SecurityStamp = "eb468a8b-1c4f-4e34-b4a0-cbd551586235",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 9, 983, DateTimeKind.Utc).AddTicks(4816),
                            UserName = "user2@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("30a4345d-df2e-46ab-8c0e-d38a7933b591"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29ea31a7-c4a0-4ea4-9816-ac515a667a99",
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 94, DateTimeKind.Utc).AddTicks(9838),
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Emily Davis",
                            Gender = 2,
                            IsDelete = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "USER3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIc+Y400VYR82NFI4siOFt/rP8/B0xUZtsFM/R9HpWqzXghgV/YNqT0woKOurBbUSA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "https://avatarfiles.alphacoders.com/151/thumb-151233.jpg",
                            SecurityStamp = "10699d95-cc66-46f5-9316-2ec89adf4c3f",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 94, DateTimeKind.Utc).AddTicks(9842),
                            UserName = "user3@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("594f8fe1-1cf1-4f5a-a8ae-6b9509fbf283"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11a1f72b-4f71-4a18-9374-42e57a11ad9b",
                            CreatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 192, DateTimeKind.Utc).AddTicks(9545),
                            Email = "user4@gmail.com",
                            EmailConfirmed = false,
                            FullName = "David Lee",
                            Gender = 1,
                            IsDelete = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "USER4@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMKwgJF1XF9gxnVciQHc0q6xCcn7YgnXmeCGWTatwwKk6aXpazZv9CyA+bN8a9jkXA==",
                            PhoneNumberConfirmed = false,
                            PictureUrl = "https://avatarfiles.alphacoders.com/151/thumb-151233.jpg",
                            SecurityStamp = "c303c596-5245-4183-9563-d5835001e673",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedDateTime = new DateTime(2024, 5, 16, 4, 23, 10, 192, DateTimeKind.Utc).AddTicks(9553),
                            UserName = "user4@gmail.com"
                        });
                });

            modelBuilder.Entity("AppUserIdentityRole<Guid>", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("IdentityRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Address", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("Shoppy.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("Shoppy.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Product", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.ProductRating", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppy.Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.RatingResource", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.ProductRating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Shoppy.Persistence.Identity.AppUser", b =>
                {
                    b.HasOne("Shoppy.Domain.Entities.Cart", "Cart")
                        .WithOne()
                        .HasForeignKey("Shoppy.Persistence.Identity.AppUser", "CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shoppy.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
